// <auto-generated />
using System;
using Artsofte.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artsofte.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230426144005_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Artsofte.DAL.Models.Departament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departaments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2aa8b6de-a94b-4a61-8de2-1c1dd3081d9b"),
                            Floor = 4,
                            Name = "AI"
                        },
                        new
                        {
                            Id = new Guid("37eeb94e-0af2-47fe-8fb7-1020eb2d965f"),
                            Floor = 5,
                            Name = "Analytics"
                        },
                        new
                        {
                            Id = new Guid("d27b4d10-c4f7-46c6-be3f-13b3e7dc2614"),
                            Floor = 3,
                            Name = "GameDev"
                        });
                });

            modelBuilder.Entity("Artsofte.DAL.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Artsofte.DAL.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecd57f42-d96e-481c-a6e7-f13061531059"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("19e545ad-bd0b-42e4-ac4f-4e1de9274dda"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("651709a0-5eb1-45d7-8f7f-122dc1bfa066"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("c810e669-1840-4af7-8f50-d47cfc25a3fe"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("091dfd53-a344-4dad-aea0-6399e871ec6c"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("57d5dd46-4a64-45ec-800f-fd299cba761f"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("7e2a4608-f5e1-4ba5-a7ed-d7516f7803e8"),
                            Name = "Кумир"
                        });
                });

            modelBuilder.Entity("Artsofte.DAL.Models.Employee", b =>
                {
                    b.HasOne("Artsofte.DAL.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Artsofte.DAL.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departament");

                    b.Navigation("ProgrammingLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
