// <auto-generated />
using System;
using Artsofte.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Artsofte.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Artsofte.DAL.Models.Departament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departaments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9274e70-c65c-4a16-b225-663c34bc6363"),
                            Floor = 4,
                            Name = "AI"
                        },
                        new
                        {
                            Id = new Guid("7e044f87-61ca-4379-9612-4b732dfbdad5"),
                            Floor = 5,
                            Name = "Analytics"
                        },
                        new
                        {
                            Id = new Guid("309ae420-177a-41b3-8da9-aa39280f19c3"),
                            Floor = 3,
                            Name = "GameDev"
                        });
                });

            modelBuilder.Entity("Artsofte.DAL.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<Guid?>("DepartamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProgrammingLanguageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentId");

                    b.HasIndex("ProgrammingLanguageId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Artsofte.DAL.Models.ProgrammingLanguage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProgrammingLanguages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f95e39b-83af-47e2-9dad-c3faff4fb7fb"),
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("30d8f615-8378-4343-8aaf-7505bcbae688"),
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("93077adb-6815-47f2-a901-68444c2cc8dd"),
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("2010bf49-978e-4c50-9c90-17526e35660b"),
                            Name = "Scala"
                        },
                        new
                        {
                            Id = new Guid("35277897-a6bb-450e-b5f9-b4865a8a25fb"),
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("48f5d342-647f-4dd1-afc8-b6f30c6e22be"),
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = new Guid("8e195f00-3b2e-4075-8386-ab19960dbabd"),
                            Name = "Кумир"
                        });
                });

            modelBuilder.Entity("Artsofte.DAL.Models.Employee", b =>
                {
                    b.HasOne("Artsofte.DAL.Models.Departament", "Departament")
                        .WithMany()
                        .HasForeignKey("DepartamentId");

                    b.HasOne("Artsofte.DAL.Models.ProgrammingLanguage", "ProgrammingLanguage")
                        .WithMany()
                        .HasForeignKey("ProgrammingLanguageId");

                    b.Navigation("Departament");

                    b.Navigation("ProgrammingLanguage");
                });
#pragma warning restore 612, 618
        }
    }
}
